### ISSUE TITLE
TTT Bug

### ISSUE THREAD

**Issue by comedinha** [Kefta/Entity-Crash-Catcher#14]
When the anti cheat remove a player corpse it bug
```
TTT:   The Server found the body of . He was innocent.
TTT:   The Server found the body of . He was innocent.
TTT:   The Server found the body of . He was innocent.
TTT:   The Server found the body of . He was innocent.
TTT:   The Server found the body of . He was innocent.
```

Not identify player and all removed is innocent.

**Comment by Kefta** [comment]
That doesn't help at all. I can't work around your anti-cheat

**Comment by comedinha** [comment]
I'm testing on more maps basically when ttt_airbus people fall from the plane this error occurs.

**Comment by Kefta** [comment]
@comedinha Does it cause any other glitches/errors or just that console print?

**Comment by comedinha** [comment]
No errors

**Comment by comedinha** [comment]
The map ttt_aircraft have same problem

**Comment by Kefta** [comment]
I'll just add a check to not print the check if the body has no name

**Comment by comedinha** [comment]
When the corpse is remove give some script bugs, the ply give invalid...
Error in hook PostDrawHUD: addons/advttt/lua/autorun/client/cl_advancedttt.lua:73: attempt to call method 'Alive' (a nil value)
stack traceback:
	addons/advttt/lua/autorun/client/cl_advancedttt.lua:73: in function 'fn'
	addons/ulib/lua/ulib/shared/hook.lua:110: in function <addons/ulib/lua/ulib/shared/hook.lua:93>
	[C]: in function '‭‬‌⁬﻿‎⁯⁮⁭'

[ERROR] 

and errors on ttt cl_targetid, give client invalid

**Comment by comedinha** [comment]
If i remove the Crash Catcher the bug stop

**Comment by comedinha** [comment]
Other bug, when player respawn:
![2015-11-22_00001](https://cloud.githubusercontent.com/assets/5075051/11326315/ba2824ce-914d-11e5-9ad5-34a70514aa7d.jpg)

I believe the ent is being treated as a player, not as ragdoll
```
ent:IsPlayer()
```

**Comment by Kefta** [comment]
Okay, I'll remove players from the unreasonable physics list completely and just nan check them separately

**Comment by comedinha** [comment]
No news to fix?

**Comment by Kefta** [comment]
On vacation; can't do it from my phone

**Comment by whatnonamer** [comment]
No news to fix? :)

**Comment by comedinha** [comment]
Fixed, but if a launch a player he is removed from server and bug...
Ragdolls are fixed...

**Comment by whatnonamer** [comment]
What? I still crash..

**Comment by comedinha** [comment]
Lol, no more crashes for me...

**Comment by Kefta** [comment]
@whatnonamer Than either you need to adjust the values, or the crashes you're having aren't Ragdoll related

**Comment by Kefta** [comment]
@whatnonamer @comedinha Should be fixed. Please test!
