### ISSUE TITLE
Two Errors

### ISSUE THREAD

**Issue by Maksimo007** [Kefta/Entity-Crash-Catcher#15]
I have two errors which are very annoying.

[ERROR] addons/ragdollremover/lua/autorun/ragdollremover.lua:113: attempt to call field 'SetFound' (a nil value)
  1. IdentifyCorpse - addons/ragdollremover/lua/autorun/ragdollremover.lua:113
   2. fn - addons/ragdollremover/lua/autorun/ragdollremover.lua:165
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

[ERROR] addons/ragdollremover/lua/autorun/ragdollremover.lua:113: attempt to call field 'SetFound' (a nil value)
  1. IdentifyCorpse - addons/ragdollremover/lua/autorun/ragdollremover.lua:113
   2. fn - addons/ragdollremover/lua/autorun/ragdollremover.lua:165
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

Hopefully you can help me.

Maksimo007

**Comment by Kefta** [comment]
Are you running TTT? If so, can you tell me what the result of this is in console?

lua_run print( FindMetaTable( "Player" ).SetFound )

**Comment by Maksimo007** [comment]
Yes, it is TTT.
> print( FindMetaTable( "Player" ).SetFound )...
nil

**Comment by Kefta** [comment]
Could you try lua_run print( CORPSE.SetFound )

**Comment by Maksimo007** [comment]
Yes, here:
lua_run print( CORPSE.SetFound )
> print( CORPSE.SetFound )...
function: 0xea261ab0

**Comment by Maksimo007** [comment]
So what can I do?

**Comment by Kefta** [comment]
What colour are the errors?

**Comment by Maksimo007** [comment]
They do not really have a color. I type the commands into the server console and there aren't any colors. If I type it in the client console, nothing happens.
Oh I see I forgot one error:

[ERROR] addons/ragdollremover/lua/autorun/gs_crashcatcher.lua:178: attempt to call global 'ServerLog' (a nil value)
  1. fn - addons/ragdollremover/lua/autorun/gs_crashcatcher.lua:178
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

Maybe this helps.

**Comment by Kefta** [comment]
@Maksimo007 Make sure you are running the script serverside, NOT shared.
