### ISSUE TITLE
Update comments

### ISSUE THREAD

**Issue by Kefta** [Kefta/Entity-Crash-Catcher#19]

**Comment by DH1806** [comment]
No crashes until now, I'll keep you updated.

**Comment by comedinha** [comment]
Have errors for me

**Comment by Kefta** [comment]
@comedinha What errors?

**Comment by DH1806** [comment]
yes i saw them now also.
[ERROR] lua/autorun/server/gs_crashcatcher.lua:138: attempt to get length of global 'EntList' (a nil value)
1. fn - lua/autorun/server/gs_crashcatcher.lua:138
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:357

**Comment by comedinha** [comment]
```sdfsdf```
L 01/31/2016 - 09:05:55: Lua Error: 
[ERROR] addons/helpers/lua/autorun/server/gs_crashcatcher.lua:229: table index is nil
  1. fn - addons/helpers/lua/autorun/server/gs_crashcatcher.lua:229
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:1

L 01/31/2016 - 17:08:21: Lua Error: 
[ERROR] addons/helpers/lua/autorun/server/gs_crashcatcher.lua:138: attempt to get length of global 'EntList' (a nil value)
  1. fn - addons/helpers/lua/autorun/server/gs_crashcatcher.lua:138
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by Kefta** [comment]
@DH1806 @comedinha Try now
