### ISSUE TITLE
Call Detective doesnt work any more?

### ISSUE THREAD

**Issue by DH1806** [Kefta/Entity-Crash-Catcher#20]
Im not 100% sure if it's caused by this script, but since i put it in i get this error when calling detective:
[DH1806|70|STEAM_0:1:41686167] Lua Error:
[ERROR] gamemodes/terrortown/gamemode/corpse.lua:151: attempt to call global 'GetDetectiveFilter' (a nil value)
1. unknown - gamemodes/terrortown/gamemode/corpse.lua:151
2. unknown - lua/includes/modules/concommand.lua:54

I can try it out 100% sure this evening but not now :/ maybe some others have the problem too?

**Comment by Kefta** [comment]
Can't replicate

**Comment by comedinha** [comment]
Not is error of this anti crash...

**Comment by DH1806** [comment]
Server just crashed:

ServerLog: 03:10.32 - DMG: Der Kingsman [traitor] damaged N1kmido [innocent] for 22 dmg
L 02/02/2016 - 21:58:39: 03:10.32 - DMG: Der Kingsman [traitor] damaged N1kmido [innocent] for 22 dmg
Player [8][Der Kingsman]
ServerLog: 03:10.32 - KILL:	Der Kingsman [traitor] killed N1kmido [innocent]
L 02/02/2016 - 21:58:39: 03:10.32 - KILL:	Der Kingsman [traitor] killed N1kmido [innocent]
ServerLog: [GS] Removed N1kmido for moving too fast (3960.000000)
L 02/02/2016 - 21:58:43: [GS] Removed N1kmido for moving too fast (3960.000000)
ServerLog: [GS] Removed prop_physics for moving too fast (3960.000000)
L 02/02/2016 - 21:58:43: [GS] Removed prop_physics for moving too fast (3960.000000)
Player [12][No_quarter_4u]
ServerLog: [GS] Removed N1kmido for moving too fast (3960.000000)
L 02/02/2016 - 21:58:44: [GS] Removed N1kmido for moving too fast (3960.000000)
ServerLog: [GS] Removed prop_physics for moving too fast (3960.000244)
L 02/02/2016 - 21:58:44: [GS] Removed prop_physics for moving too fast (3960.000244)
ServerLog: [GS] Removed N1kmido for moving too fast (3960.000000)
L 02/02/2016 - 21:58:45: [GS] Removed N1kmido for moving too fast (3960.000000)
ServerLog: [GS] Removed prop_physics for moving too fast (3960.000244)
L 02/02/2016 - 21:58:45: [GS] Removed prop_physics for moving too fast (3960.000244)
Crazy physics on [315][prop_physics] [Ang:-nan,nan,180.000000] [Pos:-nan,-nan,nan] - removing
prop_ragdoll[314]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.

**Comment by Kefta** [comment]
@DH1806 Huh? Doesn't seem to be removing them correctly. Can you please try and change the think time Convar to 0 and report back the results?

**Comment by DH1806** [comment]
Okay, I'll keep you updated whether there is another crash.

**Comment by DH1806** [comment]
ServerLog: 03:51.09 - KILL:	_Karate_WreaZz [traitor] killed _Karate_WreaZz [traitor]
L 02/04/2016 - 01:00:16: 03:51.09 - KILL:	_Karate_WreaZz [traitor] killed _Karate_WreaZz [traitor]
ServerLog: [GS] Removed KamelEsel02 for moving too fast (4342.430664)
L 02/04/2016 - 01:00:16: [GS] Removed KamelEsel02 for moving too fast (4342.430664)
ServerLog: [GS] Removed _Karate_WreaZz for moving too fast (4715.096680)
L 02/04/2016 - 01:00:16: [GS] Removed _Karate_WreaZz for moving too fast (4715.096680)
ServerLog: Round ended.
L 02/04/2016 - 01:00:20: Round ended.
ServerLog: Result: traitors win.
L 02/04/2016 - 01:00:20: Result: traitors win.


After this Log the server crashed.

**Comment by Kefta** [comment]
I see no indication that the crash came from physics

**Comment by DH1806** [comment]
yes i also don't, but i was wondering what caused this crash and i wanted to show you the script because just before the crash there was something removed from moving too fast.
but seems like removing is working now

**Comment by Kefta** [comment]
Pushed out an experimental change; please test

**Comment by Kefta** [comment]
Okay, I pushed out a new version that should fix the nan issues in theory. Please post any new logs and info to the issue here: https://github.com/Kefta/Entity-Crash-Catcher/issues/18
