### ISSUE TITLE
Server crashed again

### ISSUE THREAD

**Issue by DH1806** [Kefta/Entity-Crash-Catcher#21]
Log:

L 02/07/2016 - 01:05:33: Round ended.
ServerLog: Result: innocent win.
L 02/07/2016 - 01:05:33: Result: innocent win.
Clamping SetLocalVelocity(1204.012451,-798.749084,-8193.648438) on gmod_hands (928)
prop_ragdoll[264]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.
Crazy physics on [407][prop_physics] [Ang:-nan,nan,180.000000] [Pos:-nan,-nan,nan] - removing

**Comment by DH1806** [comment]
Edit: This isnt with the version that was posted 16 hours ago but with the one before.

**Comment by Kefta** [comment]
Try the new one

**Comment by DH1806** [comment]
Okay it's online, i'll keep you updated.

**Comment by DH1806** [comment]
I'm sorry, but it still crashed due nan issue :/

Spieler Kaneki hat den Server verlassen.
Dropped Kaneki from server (Disconnect by user.)
ServerLog: [GS] Removed prop_physics (ID: 917) for moving too fast (3791.627197)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 917) for moving too fast (3791.627197)
ServerLog: [GS] Removed prop_physics (ID: 918) for moving too fast (2282.809082)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 918) for moving too fast (2282.809082)
ServerLog: [GS] Removed prop_physics (ID: 920) for moving too fast (3433.826904)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 920) for moving too fast (3433.826904)
ServerLog: [GS] Removed prop_physics (ID: 921) for moving too fast (2636.757568)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 921) for moving too fast (2636.757568)
ServerLog: [GS] Removed prop_physics (ID: 922) for moving too fast (7675.705078)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 922) for moving too fast (7675.705078)
ServerLog: [GS] Removed prop_physics (ID: 923) for moving too fast (3737.031250)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 923) for moving too fast (3737.031250)
ServerLog: [GS] Removed prop_physics (ID: 924) for moving too fast (7637.398926)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 924) for moving too fast (7637.398926)
ServerLog: [GS] Removed prop_physics (ID: 925) for moving too fast (7780.818359)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 925) for moving too fast (7780.818359)
ServerLog: [GS] Removed prop_physics (ID: 926) for moving too fast (2743.129150)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 926) for moving too fast (2743.129150)
ServerLog: [GS] Removed prop_physics (ID: 927) for moving too fast (4148.924316)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 927) for moving too fast (4148.924316)
ServerLog: [GS] Removed prop_physics (ID: 928) for moving too fast (2256.878906)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 928) for moving too fast (2256.878906)
ServerLog: [GS] Removed prop_physics (ID: 929) for moving too fast (7620.155762)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 929) for moving too fast (7620.155762)
ServerLog: [GS] Removed prop_physics (ID: 930) for moving too fast (3125.737305)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 930) for moving too fast (3125.737305)
ServerLog: [GS] Removed prop_physics (ID: 931) for moving too fast (7821.810059)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 931) for moving too fast (7821.810059)
ServerLog: [GS] Removed prop_physics (ID: 932) for moving too fast (3612.687988)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 932) for moving too fast (3612.687988)
ServerLog: [GS] Removed prop_physics (ID: 934) for moving too fast (7443.433105)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 934) for moving too fast (7443.433105)
ServerLog: [GS] Removed prop_physics (ID: 936) for moving too fast (7536.479980)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 936) for moving too fast (7536.479980)
ServerLog: [GS] Removed prop_physics (ID: 937) for moving too fast (6438.917969)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 937) for moving too fast (6438.917969)
ServerLog: [GS] Removed prop_physics (ID: 938) for moving too fast (2377.595947)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 938) for moving too fast (2377.595947)
ServerLog: [GS] Removed prop_physics (ID: 939) for moving too fast (3850.736572)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 939) for moving too fast (3850.736572)
ServerLog: [GS] Removed prop_physics (ID: 940) for moving too fast (7674.890625)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 940) for moving too fast (7674.890625)
ServerLog: [GS] Removed prop_physics (ID: 941) for moving too fast (7818.069824)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 941) for moving too fast (7818.069824)
ServerLog: [GS] Removed prop_physics (ID: 943) for moving too fast (7239.185059)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 943) for moving too fast (7239.185059)
ServerLog: [GS] Removed prop_physics (ID: 945) for moving too fast (7613.417480)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 945) for moving too fast (7613.417480)
ServerLog: [GS] Removed prop_physics (ID: 946) for moving too fast (3999.999756)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 946) for moving too fast (3999.999756)
ServerLog: [GS] Removed prop_physics (ID: 947) for moving too fast (4000.000000)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 947) for moving too fast (4000.000000)
ServerLog: [GS] Removed prop_physics (ID: 948) for moving too fast (7306.897461)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 948) for moving too fast (7306.897461)
ServerLog: [GS] Removed prop_physics (ID: 949) for moving too fast (7952.942383)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 949) for moving too fast (7952.942383)
ServerLog: [GS] Removed prop_physics (ID: 950) for moving too fast (7727.834961)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 950) for moving too fast (7727.834961)
ServerLog: [GS] Removed prop_physics (ID: 951) for moving too fast (2673.490234)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 951) for moving too fast (2673.490234)
ServerLog: [GS] Removed prop_physics (ID: 953) for moving too fast (7586.150391)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 953) for moving too fast (7586.150391)
ServerLog: [GS] Removed prop_physics (ID: 954) for moving too fast (3611.633789)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 954) for moving too fast (3611.633789)
ServerLog: [GS] Removed prop_physics (ID: 955) for moving too fast (3490.000488)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 955) for moving too fast (3490.000488)
ServerLog: [GS] Removed prop_physics (ID: 958) for moving too fast (2709.577148)
L 02/08/2016 - 15:17:09: [GS] Removed prop_physics (ID: 958) for moving too fast (2709.577148)
prop_ragdoll[297]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.

**Comment by DH1806** [comment]
ServerLog: 01:01.08 - DMG: lagger43 [traitor] damaged Matze [innocent] for 125 dmg
L 02/08/2016 - 18:57:44: 01:01.08 - DMG: lagger43 [traitor] damaged Matze [innocent] for 125 dmg
Player [9][lagger43]
ServerLog: 01:01.08 - KILL:	lagger43 [traitor] killed Matze [innocent]
L 02/08/2016 - 18:57:44: 01:01.08 - KILL:	lagger43 [traitor] killed Matze [innocent]
ServerLog: [GS] Removed prop_physics (ID: 29) for moving too fast (3999.999756)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 29) for moving too fast (3999.999756)
ServerLog: [GS] Removed prop_physics (ID: 51) for moving too fast (3999.999756)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 51) for moving too fast (3999.999756)
ServerLog: [GS] Removed prop_physics (ID: 95) for moving too fast (2131.512207)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 95) for moving too fast (2131.512207)
ServerLog: [GS] Removed prop_physics (ID: 96) for moving too fast (2083.796143)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 96) for moving too fast (2083.796143)
ServerLog: [GS] Removed prop_physics (ID: 99) for moving too fast (2106.382568)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 99) for moving too fast (2106.382568)
ServerLog: [GS] Removed prop_physics (ID: 102) for moving too fast (2668.539795)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 102) for moving too fast (2668.539795)
ServerLog: [GS] Removed prop_physics (ID: 103) for moving too fast (2358.125488)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 103) for moving too fast (2358.125488)
ServerLog: [GS] Removed prop_physics (ID: 104) for moving too fast (2294.561768)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 104) for moving too fast (2294.561768)
ServerLog: [GS] Removed prop_physics (ID: 105) for moving too fast (2338.557861)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 105) for moving too fast (2338.557861)
ServerLog: [GS] Removed prop_physics (ID: 106) for moving too fast (2601.718506)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 106) for moving too fast (2601.718506)
ServerLog: [GS] Removed prop_physics (ID: 107) for moving too fast (2771.623291)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 107) for moving too fast (2771.623291)
ServerLog: [GS] Removed prop_physics (ID: 109) for moving too fast (3144.175293)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 109) for moving too fast (3144.175293)
ServerLog: [GS] Removed prop_physics (ID: 110) for moving too fast (2874.392822)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 110) for moving too fast (2874.392822)
ServerLog: [GS] Removed prop_physics (ID: 111) for moving too fast (2616.603760)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 111) for moving too fast (2616.603760)
ServerLog: [GS] Removed prop_physics (ID: 113) for moving too fast (3234.672607)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 113) for moving too fast (3234.672607)
ServerLog: [GS] Removed prop_physics (ID: 114) for moving too fast (3223.515137)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 114) for moving too fast (3223.515137)
ServerLog: [GS] Removed prop_physics (ID: 116) for moving too fast (3223.454346)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 116) for moving too fast (3223.454346)
ServerLog: [GS] Removed prop_physics (ID: 117) for moving too fast (2736.244385)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 117) for moving too fast (2736.244385)
ServerLog: [GS] Removed prop_physics (ID: 118) for moving too fast (2983.037842)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 118) for moving too fast (2983.037842)
ServerLog: [GS] Removed prop_physics (ID: 119) for moving too fast (2865.321045)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 119) for moving too fast (2865.321045)
ServerLog: [GS] Removed prop_physics (ID: 120) for moving too fast (3104.718750)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 120) for moving too fast (3104.718750)
ServerLog: [GS] Removed prop_physics (ID: 121) for moving too fast (3443.352783)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 121) for moving too fast (3443.352783)
ServerLog: [GS] Removed prop_physics (ID: 123) for moving too fast (2994.503662)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 123) for moving too fast (2994.503662)
ServerLog: [GS] Removed prop_physics (ID: 124) for moving too fast (2824.963867)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 124) for moving too fast (2824.963867)
ServerLog: [GS] Removed prop_physics (ID: 125) for moving too fast (2970.801758)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 125) for moving too fast (2970.801758)
ServerLog: [GS] Removed prop_physics (ID: 167) for moving too fast (4000.000244)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 167) for moving too fast (4000.000244)
ServerLog: [GS] Removed prop_physics (ID: 168) for moving too fast (4000.000000)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 168) for moving too fast (4000.000000)
ServerLog: [GS] Removed prop_physics (ID: 169) for moving too fast (3999.999756)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 169) for moving too fast (3999.999756)
ServerLog: [GS] Removed prop_physics (ID: 623) for moving too fast (3999.999756)
L 02/08/2016 - 18:57:44: [GS] Removed prop_physics (ID: 623) for moving too fast (3999.999756)
prop_ragdoll[321]:SetAbsOrigin( -nan -nan nan ): Ignoring unreasonable position.


A C4 that just exploded caused this crash.

**Comment by Kefta** [comment]
Okay, I'm convinced an addon has to be causing it. This is just too frequent

**Comment by DH1806** [comment]
It was because of all the props flying around and the addon might have thoght that they would move too fast...
I don't know which addon could cause this, I have more than 100 addons on my server and to test it all would need soo much time...maybe i can check with someone else who has the problem whether we have some equal addons so we can test these.
I could also give you a list of my addons and you could think about which of these could cause it.

**Comment by Kefta** [comment]
Just remove half at a time and pare down to about a possible list of 10

**Comment by DH1806** [comment]
Problem is that I can't really produce the error, it happens randomly just at some time, sometimes after like 2 or 3 days, so we would have to play maybe 3 days or more without half of all addons.

**Comment by comedinha** [comment]
Try use the https://github.com/Kefta/Entity-Crash-Catcher/blob/3d23033ed33d2330d5ab87a3505c0f2c0aa47d39/lua/autorun/server/gs_crashcatcher.lua...

**Comment by Kefta** [comment]
@comedinha Why an old version?

**Comment by comedinha** [comment]
I do not know why but this version work better e.e

On my server went days without giving crash
I put again and already is two days without crashes

**Comment by Kefta** [comment]
And this is with what options enabled exactly?

**Comment by comedinha** [comment]
default options, no need changes
