### ISSUE TITLE
Instantly Removing Body

### ISSUE THREAD

**Issue by mrvideofreak2010** [Kefta/Entity-Crash-Catcher#22]
Whenever I use a custom model and I die, it instantly removes it and it's so annoying.

**Comment by Kefta** [comment]
Does it print anything in console with a [GS] tag?

**Comment by mrvideofreak2010** [comment]
You mean in-game? It does the print.

Also some of the bodies go t-posed

**Comment by mrvideofreak2010** [comment]
ServerLog: [GS] Removed [VG} MrVideoFreak (ID: 536) for moving too fast (15506185494407659000000000000.000000)

**Comment by mrvideofreak2010** [comment]
ServerLog: [GS] Removed [VG} MrVideoFreak (ID: 220) for moving too fast (4108660130967923700000000000.000000)

**Comment by comedinha** [comment]
4108660130967923700000000000 = your server probably crash if the ragdoll not be removed

**Comment by Kefta** [comment]
Sounds like a model problem

**Comment by mrvideofreak2010** [comment]
I've had no problems with this, this started to become a thing when garry updated gmod
